export const products = [
    {
      id: 1,
      title: "Digital Watch",
      description: "black in color",
      initPrice: "150",
      price: "150",
      img: "/image/digitalwatch.jpg",
      quantity: 1,
    },
    {
      id: 2,
      title: "Laptop",
      description: "white in color",
      initPrice: "2300",
      price: "2300",
      img: "/image/laptop.jpg",
      quantity: 1,
    },
    {
      id: 3,
      title: "Tablet",
      description: "black in color",
      initPrice: "3500",
      price: "3500",
      img: "/image/tablet.jpg",
      quantity: 1,
    },
    {
      id: 4,
      title: "Tablet 12",
      description: "Best mobile ever",
      initPrice: "90500",
      price: "90500",
      img: "/image/tablet2.jpg",
      quantity: 1,
    },
    {
      id: 5,
      title: "Digital Watch",
      description: "black in color",
      initPrice: "2500",
      price: "2500",
      img: "/image/digitalwatch.jpg",
      quantity: 1,
    },
    {
      id: 6,
      title: "Laptop",
      description: "black in color",
      initPrice: "3500",
      price: "3500",
      img: "/image/laptop.jpg",
      quantity: 1,
    },
    {
      id: 7,
      title: "Digital Watch",
      description: "black in color",
      initPrice: "2500",
      price: "2500",
      img: "/image/digitalwatch.jpg",
      quantity: 1,
    },
    {
      id: 8,
      title: "Iphone 12",
      description: "Best mobile ever",
      initPrice: "90500",
      price: "90500",
      img: "/image/laptop.jpg",
      quantity: 1,
    },
    {
      id: 9,
      title: "Digital Watch",
      description: "black in color",
      initPrice: "2500",
      price: "2500",
      img: "/image/digitalwatch.jpg",
      quantity: 1,
    },
  ];
  